global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['prometheus:9000']
        labels:
          application: api-gateway
          environment: demo
  - job_name: 'product-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080'] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: product-service
          environment: demo
  - job_name: 'inventory-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082'] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: inventory-service
          environment: demo
  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081'] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: order-service
          environment: demo
  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8083'] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: notification-service
          environment: demo
